program: cosmobot_deep_learning/models/simple_cnn.py
method: grid
metric:
  name: val_loss
  goal: minimize
parameters:
  desired-train-sample-count:
    values: [10, 10, 100, 100, 1000, 1000, 10000, 10000]