program: cosmobot_deep_learning/models/simple_cnn.py
method: grid
metric:
  name: val_loss
  goal: minimize
parameters:
  desired-train-sample-count:
    values: [30, 30, 30, 100, 100, 100, 300, 300, 300, 1000, 1000, 1000, 3000, 3000, 10000, 10000, 10000]