program: cosmobot_deep_learning/models/simple_cnn.py
method: grid
metric:
  name: val_loss
  goal: minimize
parameters:
  desired-train-sample-count:
    values: [500, 1000, 1500, 2000, 2500, 3000, 3500, 4000, 4500, 5000, 5500, 6000, 6500, 7000]